## Copyright (C) 2025 Intel Corporation
##
## SPDX-License-Identifier: BSD-3-Clause

apiVersion: v2
name: ai-suite-microservice
type: application
description: Helm chart for deploying Intel Media and Entertainment AI Suite
version: 1.0.0
appVersion: ivsr_raisr:25.04-alpha
home: https://github.com/OpenVisualCloud/Media-Entertainment-AI-Suite

maintainers:
  - name: Dong Jerry
    email: jerry.dong@intel.com
  - name: Linkiewicz Milosz
    email: milosz.linkiewicz@intel.com

keywords:
  - ai
  - ivsr
  - raisr
  - intel
  - openvisualcloud

sources:
  - https://github.com/OpenVisualCloud
  - https://github.com/OpenVisualCloud/Video-Super-Resolution-Library
  - https://github.com/OpenVisualCloud/iVSR
  - https://github.com/OpenVisualCloud/Media-Transport-Library
