# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Set directory path of test video and output and models
test_video_dir: /home/spr-lxx/workspace/aime_cemp_mwc/demo_video/bbb/input/
output_dir: /home/spr-lxx/workspace/output/
# Set directory path which include IR file (.xml and .bin)
model_dir: /home/spr-lxx/workspace/ivsr/ivsr_2024.05/SVP_Basic/dunet_2024.01/INT8-performance/

# Filter Configuration
# Set `selected` to true to select either ivsr or raisr for video processing.
# Refer to the documentation of ivsr and raisr for configuration details.
filter_parameters:
  ivsr:
    selected: true
    configuration:
      format: rgb24
      model_name: dunet.xml
      nif: 1
      model_type: 1
      normalize_factor: 1.0
      device: CPU

  raisr:
    selected: false
    configuration:
      threadcount: 20
      ratio: 2
      bits: 8
      passes: 1
      asm: avx512
      filterfolder: filters_2x/filters_highres

# Specify codec parameter, current supports libx264 and libx265 encoders
codec_parameters:
  encoder: libx264
  bitrate: 5M
  profile: main
  pix_fmt: yuv420p
