name: Anti Virus Scan

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

defaults:
  run:
    shell: bash

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  anti-virus-scan-ubuntu:
    runs-on: "ubuntu-22.04"
    timeout-minutes: 30
    steps:
      - name: "Harden Runner"
        uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
        with:
          egress-policy: audit

      - name: "Checkout repository"
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: "Git Anti Virus Scan"
        uses: "hugoalh/scan-virus-ghaction@6fd3ce3d07abc68dd032bd99eebb8cce12986a9d" # v.0.20.1
