name: Docker Build

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  DOCKER_REGISTRY: "ghcr.io"
  DOCKER_REGISTRY_PREFIX: "openvisualcloud/media-entertainment-ai-suite"
  DOCKER_IMAGE_NAME: "ivsr_raisr"
  DOCKER_IMAGE_TAG: "${{ github.sha }}"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  ivsr-image-build:
    name: Build sdk Docker Image
    uses: ./.github/workflows/build_docker_tpl.yml
    permissions:
      contents: read
      security-events: write
    with:
      docker_registry: "${{ env.DOCKER_REGISTRY }}"
      docker_registry_prefix: "${{ env.DOCKER_REGISTRY_PREFIX }}"
      docker_file_path:  "Dockerfile"
      docker_image_name: "${{ env.DOCKER_IMAGE_NAME }}"
      docker_image_tag: "${{ env.DOCKER_IMAGE_TAG }}"

  ivsr-container-test:
    runs-on: ubuntu-22.04
    container:
      image: "${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_REGISTRY_PREFIX }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }}"
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: Run ffmpeg iVSR plugin help
        run: ./ffmpeg/ffmpeg -help filter=dnn_processing

      - name: Run ffmpeg raisr plugin help
        run: ./ffmpeg/ffmpeg -help filter=raisr

      - name: Run ffmpeg raisr_opencl plugin help
        run: ./ffmpeg/ffmpeg -help filter=raisr_opencl

