name: Docker Build

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  DOCKER_REGISTRY: "ghcr.io"
  DOCKER_REGISTRY_PREFIX: "openvisualcloud/media-entertainment-ai-suite"
  DOCKER_IMAGE_NAME: "ivsr_raisr"
  DOCKER_IMAGE_TAG: "${{ github.sha }}"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  ivsr-image-build:
    name: Build sdk Docker Image
    uses: ./.github/workflows/build_docker_tpl.yml
    permissions:
      contents: write
      security-events: write
    with:
      docker_registry: "ghcr.io"
      docker_registry_prefix: "openvisualcloud/media-entertainment-ai-suite"
      docker_file_path:  "Dockerfile"
      docker_image_name: "ivsr_raisr"
      docker_image_tag: "${{ github.sha }}"
      docker_registry_login: true
      docker_registry_push: false
    secrets:
      docker_registry_login: "${{ secrets.DOCKER_REGISTRY_LOGIN }}"
      docker_registry_passkey: "${{ secrets.DOCKER_REGISTRY_PASSKEY }}"
