name: Docker Build

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  DOCKER_REGISTRY: "ghcr.io"
  DOCKER_REGISTRY_PREFIX: "openvisualcloud/media-entertainment-ai-suite"
  DOCKER_IMAGE_NAME: "ivsr_raisr"
  DOCKER_IMAGE_TAG: "${{ github.sha }}"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  ivsr-image-build:
    name: "docker build: build image"
    uses: ./.github/workflows/build_docker_tpl.yml
    permissions:
      contents: read
      packages: write
      security-events: write
    with:
      docker_registry: "ghcr.io"
      docker_registry_prefix: "openvisualcloud/media-entertainment-ai-suite"
      docker_file_path: "Dockerfile"
      docker_image_name: "ivsr_raisr"
      docker_image_tag: "${{ github.sha }}"
      docker_registry_login: true
      docker_registry_push: true
