name: Docker Build

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  ivsr-image-build:
    name: Build sdk Docker Image
    uses: ./.github/workflows/build_docker_tpl.yml
    permissions:
      contents: read
      security-events: write
    with:
      docker_file_path:  "Dockerfile"
      docker_image_name: "ivsr_raisr"
