name: Trivy
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
    inputs:
      branch:
        description: "branch to run scans on"
        default: "main"
        type: string

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  scan-fs-mode:
    permissions:
      contents: read
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
    runs-on: ubuntu-22.04
    name: "Trivy: Perform fs mode scans job"
    steps:
      - name: "Trivy: Harden Runner"
        uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
        with:
          egress-policy: audit

      - name: "Trivy: Checkout code"
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          ref: ${{ inputs.branch }}

      - name: "Trivy: Run vulnerability scanner for type=fs (out=sarif)"
        uses: aquasecurity/trivy-action@99baf0d8b4e787c3cfd7b602664c8ce60a43cd38 # v0.30.0
        with:
          scan-type: "fs"
          ignore-unfixed: true
          format: "sarif"
          output: "trivy-fs-scan-results-${{ github.event.pull_request.number || github.sha }}.sarif"
          severity: "HIGH"

      - name: "Trivy: Upload fs scan results to GitHub Security tab"
        uses: github/codeql-action/upload-sarif@b611370bb5703a7efb587f9d136a52ea24c5c38c # v3.25.11
        continue-on-error: true
        with:
          sarif_file: "trivy-fs-scan-results-${{ github.event.pull_request.number || github.sha }}.sarif"

      - name: "Trivy: Upload scan results as artifacts (out=sarif)"
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # V4.4.3
        with:
          name: "trivy-config-scan-results-sarif-${{ github.event.pull_request.number || github.sha }}"
          path: "trivy-config-scan-results-${{ github.event.pull_request.number || github.sha }}.sarif"
          retention-days: 5

  scan-config-mode:
    permissions:
      contents: read
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
    runs-on: ubuntu-22.04
    name: "Trivy: Perform config mode scans job"
    steps:
      - name: "Trivy: Harden Runner"
        uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
        with:
          egress-policy: audit

      - name: "Trivy: Checkout code"
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          ref: ${{ inputs.branch }}

      - name: "Trivy: Run vulnerability scanner for type=config (out=sarif)"
        continue-on-error: true
        uses: aquasecurity/trivy-action@99baf0d8b4e787c3cfd7b602664c8ce60a43cd38 # v0.30.0
        with:
          scan-type: config
          exit-code: "0"
          format: "sarif"
          output: "trivy-config-scan-results-${{ github.event.pull_request.number || github.sha }}.sarif"

      - name: "Trivy: Run vulnerability scanner for type=config (out=table)"
        continue-on-error: true
        uses: aquasecurity/trivy-action@99baf0d8b4e787c3cfd7b602664c8ce60a43cd38 # v0.30.0
        with:
          scan-type: config
          exit-code: "0"
          format: "table"
          output: "trivy-config-scan-results-${{ github.event.pull_request.number || github.sha }}.txt"

      - name: "Trivy: Upload scan results to GitHub Security tab"
        continue-on-error: true
        uses: github/codeql-action/upload-sarif@b611370bb5703a7efb587f9d136a52ea24c5c38c # v3.25.11
        with:
          sarif_file: "trivy-config-scan-results-${{ github.event.pull_request.number || github.sha }}.sarif"

      - name: "Trivy: Upload scan results as artifacts (out=sarif)"
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # V4.4.3
        with:
          name: "trivy-config-scan-results-sarif-${{ github.event.pull_request.number || github.sha }}"
          path: "trivy-config-scan-results-${{ github.event.pull_request.number || github.sha }}.sarif"
          retention-days: 5

      - name: "Trivy: Upload scan results as artifacts (out=table)"
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # V4.4.3
        with:
          name: "trivy-config-scan-results-table-${{ github.event.pull_request.number || github.sha }}"
          path: "trivy-config-scan-results-${{ github.event.pull_request.number || github.sha }}.txt"
          retention-days: 5
